namespace PocketLib.ViewModels;

public class ListPageViewModel
{
    // ICI C EST UNE VM QUI RECUP LE SELECT BOOK ET QUI VA ETRE ENVOYER
    // DANS UNE COMMANDE QUI APPELLE LA COMMANDE DE CHARGEMENT DU LIVRE
    // AVEC CETTE ID PUIS LA COMMANDE DE NAV
}